// config.bin - 01:23:06 05/19/25, generated in 0.04 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

#define private		0
#define protected		1
#define public		2

#define TEast		0
#define TWest		1
#define TGuerrila		2
#define TCivilian		3
#define TSideUnknown		4
#define TEnemy		5
#define TFriendly		6
#define TLogic		7

#define true	1
#define false	0

class CfgPatches {
	class AS_M57_Mortar {
		addonRootClass = "A3_Armor_F_Beta";
		requiredAddons[] = {"cba_main", "ace_interact_menu"};
		requiredVersion = 0.5;
		weapons[] = {"AS_M57_weapon","AS_M57_weapon_Basic","AS_M57_Carry","AS_M57_Postolje"};
		units[] = {"AS_M57_Mortar","AS_M57_Mortar_Bazicni","AS_M57_Sanduk","AS_M57_Sanduk_Dimne","M57_Komplet_Sanduk","AS_M57_Sanduk_Svetleca"};
		magazines[] = 
		{
			"AS_HE_M73_Krusik_0",
			"AS_HE_M73_Krusik_1",
			"AS_HE_M73_Krusik_2",
			"AS_HE_M73_Krusik_2",
			"AS_HE_M73_Krusik_3",
			"AS_HE_M73_Krusik_4",
			"AS_Dim_M73_Krusik_0",
			"AS_Dim_M73_Krusik_1",
			"AS_Dim_M73_Krusik_2",
			"AS_Dim_M73_Krusik_3",
			"AS_Dim_M73_Krusik_4",
			"AS_Svetleca_M73_Krusik_0",
			"AS_Svetleca_M73_Krusik_1",
			"AS_Svetleca_M73_Krusik_2",
			"AS_Svetleca_M73_Krusik_3",
			"AS_Svetleca_M73_Krusik_4",
			"AS_HE_M73_Krusik_25x_Basic",
			"AS_Svetleca_M73_25x_Krusik_Basic",
			"AS_Dim_M73_Krusik_25x_Basic"
			
		};
		ammo[] = {"AS_M73_60mm_ammo","AS_M73_60mm_SmokeAmmo","AS_M73_60mm_Svetleca_Ammo"};

	};
};

class Extended_PreInit_EventHandlers {
	class AS_M57_Mortar {
		init = "call compile preprocessFileLineNumbers '\AS_M57_Mortar\XEH_preInit.sqf'";
	};
};

class Extended_PostInit_EventHandlers {
	class AS_M57_Mortar {
		init = "call compile preprocessFileLineNumbers '\AS_M57_Mortar\XEH_postInit.sqf'";
	};
};

class Extended_PreStart_EventHandlers {
	class AS_M57_Mortar {
		init = "call compile preprocessFileLineNumbers '\AS_M57_Mortar\XEH_preStart.sqf'";
	};
};
class CfgMovesBasic {
	class defaultDie;	// External class reference
	
	class ManActions {
		M57_Gunner = "M57_Gunner";
	};
};

class CfgMovesMaleSdr : CfgMovesBasic {
	skeletonName = "OFP2_ManSkeleton";
	gestures = "CfgGesturesMale";
	
	class States {
		class Crew;	// External class reference
		
		class M57_Gunner : Crew {
			file = "AS_M57_Mortar\animations\2B25pose.rtm";
		};
	};
};
class Mode_SemiAuto;	// External class reference

class CfgAmmo {
	class ShellCore;	// External class reference
	
	class ShellBase : ShellCore {};
	
	class Sh_155mm_AMOS : ShellBase {};
	
	class Sh_82mm_AMOS : Sh_155mm_AMOS {};
	
	class AS_M73_60mm_ammo : Sh_82mm_AMOS 
	{
		model = "AS_M57_Mortar\Granate\M73_Krusik_Fly.p3d";
		CraterEffects = "ATRocketCrater";
		explosionEffects = "GrenadeExplosion";
		hit = 80;
		indirectHit = 40;
		indirectHitRange = 12;
		muzzleEffect = "";
		
		class CamShakeExplode {
			power = 16.4;
			duration = 1.8;
			frequency = 20;
			distance = 216.443;
		};
		
		class CamShakeHit {
			power = 82;
			duration = 0.6;
			frequency = 20;
			distance = 1;
		};
		
		class CamShakeFire {
			power = 3.00922;
			duration = 1.8;
			frequency = 20;
			distance = 72.4431;
		};
		
		class CamShakePlayerFire {
			power = 0.01;
			duration = 0.1;
			frequency = 20;
			distance = 1;
		};
	};
	class Smoke_82mm_AMOS_White;
	class AS_M73_60mm_SmokeAmmo : Smoke_82mm_AMOS_White {
		model = "AS_M57_Mortar\Granate\M73_Krusik_Dim_Fly.p3d";
		submunitionAmmo = "SmokeShellArty";
	};
	class Flare_82mm_AMOS_White;
class AS_M73_60mm_Svetleca_Ammo_P0 : Flare_82mm_AMOS_White
{
    model = "AS_M57_Mortar\Granate\M73_Krusik_Svetleca_Fly.p3d";
    triggerSpeedCoef = 1;
    effectFlare = "rhs_msk40p_flare_effect";
    brightness = 250;
    timeToLive = 105;
    triggerTime = 11;
    airFriction = 0.25;
    intensity = 200000;
	flareSize = 1.85;
};

class AS_M73_60mm_Svetleca_Ammo_P1 : Flare_82mm_AMOS_White
{
    model = "AS_M57_Mortar\Granate\M73_Krusik_Svetleca_Fly.p3d";
    triggerSpeedCoef = 1;
    effectFlare = "rhs_msk40p_flare_effect";
    brightness = 250;
    timeToLive = 105;
    triggerTime = 21;
    airFriction = 0.25;
    intensity = 200000;
	flareSize = 1.85;
};

class AS_M73_60mm_Svetleca_Ammo_P2 : Flare_82mm_AMOS_White
{
    model = "AS_M57_Mortar\Granate\M73_Krusik_Svetleca_Fly.p3d";
    triggerSpeedCoef = 1;
    effectFlare = "rhs_msk40p_flare_effect";
    brightness = 250;
    timeToLive = 105;
    triggerTime = 26;
    airFriction = 0.25;
    intensity = 200000;
	flareSize = 1.85;
};

class AS_M73_60mm_Svetleca_Ammo_P3 : Flare_82mm_AMOS_White
{
    model = "AS_M57_Mortar\Granate\M73_Krusik_Svetleca_Fly.p3d";
    triggerSpeedCoef = 1;
    effectFlare = "rhs_msk40p_flare_effect";
    brightness = 250;
    timeToLive = 105;
    triggerTime = 30;
    airFriction = 0.25;
    intensity = 200000;
	flareSize = 1.85;
};

class AS_M73_60mm_Svetleca_Ammo_P4 : Flare_82mm_AMOS_White
{
    model = "AS_M57_Mortar\Granate\M73_Krusik_Svetleca_Fly.p3d";
    triggerSpeedCoef = 1;
    effectFlare = "rhs_msk40p_flare_effect";
    brightness = 250;
    timeToLive = 105;
    triggerTime = 32.5;
    airFriction = 0.25;
    intensity = 200000;
	flareSize = 1.85;
};

};

class CfgMagazines {
	class Default;	// External class reference
	
	class CA_Magazine : Default {};
	
	class VehicleMagazine : CA_Magazine {};
	
	class 32Rnd_155mm_Mo_shells : VehicleMagazine {};
	
	class 8Rnd_82mm_Mo_shells : 32Rnd_155mm_Mo_shells {};
	
	class AS_HE_M73_Krusik : 8Rnd_82mm_Mo_shells 
	{
		scope = private;
		scopeArsenal = 2;
		author = "Neo";
		displayName = "M73 Krusik Punjenje 0";
		displayNameShort = "$";
		model = "AS_M57_Mortar\Granate\AS_HE_M73_Krusik";
		picture = "\AS_M57_Mortar\M73_HE_Pic.paa";
		descriptionShort = "$STR_TBD_MORTARS_120mm_HE_CH1_DESC";
		initSpeed = 26.94;
		mass = 30;
		count = 1;
		ammo = "AS_M73_60mm_ammo";
		type = 256;
	};	
	class AS_HE_M73_Krusik_0 : AS_HE_M73_Krusik 
	{
		scope = public;
		scopeArsenal = 2;
		author = "Neo";
		displayName = "M73 Krusik Punjenje 0";
		displayNameShort = "TR osnovno";
		model = "AS_M57_Mortar\Granate\AS_HE_M73_Krusik_0";
		picture = "\AS_M57_Mortar\M73_HE_Pic.paa";
		descriptionShort = "Max domet 523m osnovno punjenje";
		initSpeed = 82.98;
		mass = 30;
		count = 1;
		ammo = "AS_M73_60mm_ammo";
		type = 256;
	};
	class AS_HE_M73_Krusik_1 : AS_HE_M73_Krusik_0 {
		scope = public;
		scopeArsenal = 2;
		author = "Neo";
		displayName = "M73 Krusik Punjenje 1";
		displayNameShort = "TR punjenje 1";
		model = "AS_M57_Mortar\Granate\AS_HE_M73_Krusik_1";
		picture = "\AS_M57_Mortar\M73_HE_Pic.paa";
		descriptionShort = "Max domet 1072m";
		initSpeed = 118.80;
		mass = 30;
		count = 1;
		ammo = "AS_M73_60mm_ammo";
		type = 256;
		ACE_isBelt = 1;
	};
	
	class AS_HE_M73_Krusik_2 : AS_HE_M73_Krusik_1 {
		displayName = "M73 Krusik Punjenje 2";
		displayNameShort = "TR punjenje 2";
		model = "AS_M57_Mortar\Granate\AS_HE_M73_Krusik_2";
		descriptionShort = "Max domet 1632m";
		initSpeed = 146.58;
		ace_artillerytables_table = "AS_HE_M73_Krusik_2";
	};
	
	class AS_HE_M73_Krusik_3 : AS_HE_M73_Krusik_1 {
		displayName = "M73 Krusik Punjenje 3";
		displayNameShort = "TR punjenje 3";
		model = "AS_M57_Mortar\Granate\AS_HE_M73_Krusik_3";
		descriptionShort = "Max domet 2136m";
		initSpeed = 167.70;
	};
	
	class AS_HE_M73_Krusik_4 : AS_HE_M73_Krusik_1 {
		displayName = "M73 Krusik Punjenje 4";
		displayNameShort = "TR punjenje 4";
		model = "AS_M57_Mortar\Granate\AS_HE_M73_Krusik_4";
		descriptionShort = "Max domet 2220–2550m";
		initSpeed = 177.76; 
	};
	//----------------------------------------------------------
	//----------------------------------------------------------
	class AS_Svetleca_M73_Krusik : 8Rnd_82mm_Mo_shells 
	{
		scope = private;
		scopeArsenal = 2;
		author = "Neo";
		displayName = "SVT Krusik Punjenje 0";
		displayNameShort = "$";
		model = "AS_M57_Mortar\Granate\Svetleca\AS_Svetleca_M73_Krusik.p3d";
		picture = "\AS_M57_Mortar\M73_HE_Pic.paa";
		descriptionShort = "";
		initSpeed = 26.94;
		mass = 30;
		count = 1;
		ammo = "AS_M73_60mm_Svetleca_Ammo";
		type = 256;
	};	
	class AS_Svetleca_M73_Krusik_0 : AS_Svetleca_M73_Krusik 
	{
		scope = public;
		scopeArsenal = 2;
		author = "Neo";
		displayName = "SVT Krusik Punjenje 0";
		displayNameShort = "Svtl. osnovno";
		model = "AS_M57_Mortar\Granate\Svetleca\AS_Svetleca_M73_Krusik_0.p3d";
		picture = "\AS_M57_Mortar\M73_Svetleca_Pic.paa";
		descriptionShort = "Max domet 523m osnovno punjenje";
		initSpeed = 82.98;
		mass = 30;
		count = 1;
		ammo = "AS_M73_60mm_Svetleca_Ammo_P0";
		type = 256;
	};
	class AS_Svetleca_M73_Krusik_1 : AS_Svetleca_M73_Krusik_0 {
		scope = public;
		scopeArsenal = 2;
		author = "Neo";
		displayName = "SVT Krusik Punjenje 1";
		displayNameShort = "Svtl.punjenje 1";
		model = "AS_M57_Mortar\Granate\Svetleca\AS_Svetleca_M73_Krusik_1";
		picture = "\AS_M57_Mortar\M73_Svetleca_Pic.paa";
		descriptionShort = "Max domet 1072m";
		initSpeed = 118.80;
		mass = 30;
		count = 1;
		ammo = "AS_M73_60mm_Svetleca_Ammo_P1";
		type = 256;
		ACE_isBelt = 1;
	};
	
	class AS_Svetleca_M73_Krusik_2 : AS_Svetleca_M73_Krusik_1 {
		displayName = "SVT Krusik Punjenje 2";
		displayNameShort = "Svtl.punjenje 2";
		model = "AS_M57_Mortar\Granate\Svetleca\AS_Svetleca_M73_Krusik_2";
		descriptionShort = "Max domet 1632m";
		ammo = "AS_M73_60mm_Svetleca_Ammo_P2";
		initSpeed = 146.58;
	};
	
	class AS_Svetleca_M73_Krusik_3 : AS_Svetleca_M73_Krusik_1 {
		displayName = "SVT Krusik Punjenje 3";
		displayNameShort = "Svtl.punjenje 3";
		model = "AS_M57_Mortar\Granate\Svetleca\AS_Svetleca_M73_Krusik_3";
		descriptionShort = "Max domet 2136m";
		ammo = "AS_M73_60mm_Svetleca_Ammo_P3";
		initSpeed = 167.70;
	};
	
	class AS_Svetleca_M73_Krusik_4 : AS_Svetleca_M73_Krusik_1 {
		displayName = "SVT Krusik Punjenje 4";
		displayNameShort = "Svtl.punjenje 4";
		model = "AS_M57_Mortar\Granate\Svetleca\AS_Svetleca_M73_Krusik_4";
		descriptionShort = "Max domet 2220–2550m";
		ammo = "AS_M73_60mm_Svetleca_Ammo_P4";
		initSpeed = 177.76; 
	};
	//----------------------------------------------------------
	//----------------------------------------------------------
	class AS_Dim_M73_Krusik : 8Rnd_82mm_Mo_shells 
	{
		scope = private;
		scopeArsenal = 2;
		author = "Neo";
		displayName = "M73 Krusik Dimne Punjenje 0";
		displayNameShort = "$";
		model = "AS_M57_Mortar\Granate\Dimna\AS_Dim_M73_Krusik";
		picture = "\AS_M57_Mortar\M73_Dimna_Pic.paa";
		descriptionShort = "$STR_TBD_MORTARS_120mm_HE_CH1_DESC";
		initSpeed = 25;
		mass = 30;
		count = 1;
		ammo = "AS_M73_60mm_SmokeAmmo";
		type = 256;
	};	
	class AS_Dim_M73_Krusik_0 : AS_HE_M73_Krusik 
	{
		scope = public;
		scopeArsenal = 2;
		author = "Neo";
		displayName = "M73 Krusik Dimne Punjenje 0";
		displayNameShort = "Dimno punjenje osnovno";
		model = "AS_M57_Mortar\Granate\Dimna\AS_Dim_M73_Krusik_0";
		picture = "\AS_M57_Mortar\M73_Dimna_Pic.paa";
		descriptionShort = "Max domet 523mm osnovno punjenje";
		initSpeed = 82.98;
		mass = 30;
		count = 1;
		ammo = "AS_M73_60mm_SmokeAmmo";
		type = 256;
	};
	class AS_Dim_M73_Krusik_1 : AS_Dim_M73_Krusik_0 {
		scope = public;
		scopeArsenal = 2;
		author = "Neo";
		displayName = "M73 Krusik Dimne Punjenje 1";
		displayNameShort = "Dimno punjenje 1";
		model = "AS_M57_Mortar\Granate\Dimna\AS_Dim_M73_Krusik_1";
		picture = "\AS_M57_Mortar\M73_Dimna_Pic.paa";
		descriptionShort = "Max domet 1072m";
		initSpeed = 118.80;
		mass = 30;
		count = 1;
		ammo = "AS_M73_60mm_SmokeAmmo";
		type = 256;
		ACE_isBelt = 1;
	};
	
	class AS_Dim_M73_Krusik_2 : AS_Dim_M73_Krusik_1 {
		displayName = "M73 Krusik Dimne Punjenje 2";
		displayNameShort = "Dimno punjenje 2";
		model = "AS_M57_Mortar\Granate\Dimna\AS_Dim_M73_Krusik_2";
		descriptionShort = "Max domet 1632mm";
		initSpeed = 146.58; // ~895m
	};
	
	class AS_Dim_M73_Krusik_3 : AS_Dim_M73_Krusik_1 {
		displayName = "M73 Krusik Dimne Punjenje 3";
		displayNameShort = "Dimno punjenje 3";
		model = "AS_M57_Mortar\Granate\Dimna\AS_Dim_M73_Krusik_3";
		descriptionShort = "Max domet 2136mm";
		initSpeed = 167.70;
	};
	
	class AS_Dim_M73_Krusik_4 : AS_Dim_M73_Krusik_1 {
		displayName = "M73 Krusik Dimne Punjenje 4";
		displayNameShort = "Dimno punjenje 4";
		model = "AS_M57_Mortar\Granate\Dimna\AS_Dim_M73_Krusik_4";
		descriptionShort = "Max domet 1690m";
		initSpeed = 177.76; // 1690m
	};
	//---------------------------------------------------------------------------
	class AS_HE_M73_Krusik_25x_Basic : 8Rnd_82mm_Mo_shells 
	{
		scope = public;
		scopeArsenal = 2;
		author = "Neo";
		displayName = "M73 Krusik 60mm";
		displayNameShort = "";
		model = "AS_M57_Mortar\Granate\AS_HE_M73_Krusik_0";
		picture = "\AS_M57_Mortar\M73_HE_Pic.paa";
		descriptionShort = "Max domet 523m osnovno punjenje";
		initSpeed = 211;
		mass = 30;
		count = 25;
		ammo = "AS_M73_60mm_ammo";
		type = 256;
	};
	class AS_Svetleca_M73_25x_Krusik_Basic : 8Rnd_82mm_Mo_shells 
	{
		scope = public;
		scopeArsenal = 2;
		author = "Neo";
		displayName = "SVT Krusik 60mm";
		displayNameShort = "";
		model = "AS_M57_Mortar\Granate\Svetleca\AS_Svetleca_M73_Krusik_0.p3d";
		picture = "\AS_M57_Mortar\M73_Svetleca_Pic.paa";
		descriptionShort = "Max domet 523m osnovno punjenje";
		initSpeed = 211;
		mass = 30;
		count = 25;
		ammo = "AS_M73_60mm_Svetleca_Ammo";
		type = 256;
	};
	class AS_Dim_M73_Krusik_25x_Basic : 8Rnd_82mm_Mo_shells 
	{
		scope = public;
		scopeArsenal = 2;
		author = "Neo";
		displayName = "M73 Krusik Dimne 60mm";
		displayNameShort = "";
		model = "AS_M57_Mortar\Granate\Dimna\AS_Dim_M73_Krusik_0";
		picture = "\AS_M57_Mortar\M73_Dimna_Pic.paa";
		descriptionShort = "Max domet 523mm osnovno punjenje";
		initSpeed = 211;
		mass = 30;
		count = 25;
		ammo = "AS_M73_60mm_SmokeAmmo";
		type = 256;
	};
	//---------------------------------------------------------------------------
	//---------------------------------------------------------------------------
};

class CfgSoundShaders {
	class AS_M57_shot_soundshader {
		samples[] = {{"AS_M57_Mortar\sounds\2B25shot.ogg", 1}};
		volume = 2;
		range = 100;
		rangeCurve = "LinearCurve";
	};
};

class CfgSoundSets {
	class AS_M57_shot_soundset {
		soundShaders[] = {"AS_M57_shot_soundshader"};
		volumeFactor = 1.6;
		volumeCurve = "InverseSquare2Curve";
		sound3DProcessingType = "WeaponMediumShot3DProcessingType";
		distanceFilter = "weaponShotDistanceFreqAttenuationFilter";
		spatial = 1;
		doppler = 0;
		loop = 0;
	};
};

class CfgWeapons {
	class CannonCore {
		class player;	// External class reference
		class close;	// External class reference
		class short;	// External class reference
		class medium;	// External class reference
		class far;	// External class reference
	};
	class Launcher;	// External class reference
	
	class Launcher_Base_F : Launcher {
		class WeaponSlotsInfo;	// External class reference
	};
	
	class mortar_82mm : CannonCore {};
	
	class AS_M57_weapon : mortar_82mm {
		displayName = "M57 60mm Mortar";
		magazines[] = 
		{
			"AS_HE_M73_Krusik_0", 
			"AS_HE_M73_Krusik_1", 
			"AS_HE_M73_Krusik_2", 
			"AS_HE_M73_Krusik_3",
			"AS_HE_M73_Krusik_4",
			"AS_Dim_M73_Krusik_0",
			"AS_Dim_M73_Krusik_1",
			"AS_Dim_M73_Krusik_2",
			"AS_Dim_M73_Krusik_3",
			"AS_Dim_M73_Krusik_4",
			"AS_Svetleca_M73_Krusik_0",
			"AS_Svetleca_M73_Krusik_1",
			"AS_Svetleca_M73_Krusik_2",
			"AS_Svetleca_M73_Krusik_3",
			"AS_Svetleca_M73_Krusik_4"
		};
		modes[] = {"Single1"};
		reloadSound[] = {"A3\Sounds_F\arsenal\weapons_static\Mortar\reload_mortar", 1, 1, 20};
		reloadMagazineSound[] = {"A3\Sounds_F\arsenal\weapons_static\Mortar\reload_mortar", 1, 1, 20};
		magazineReloadTime = 0.5;
		
		class Single1 : Mode_SemiAuto {
			displayName = "M57 Mortar";
			sounds[] = {"StandardSound"};
			
			class StandardSound {
				soundSetShot[] = {"AS_M57_shot_soundset"};
			};
			reloadSound[] = {"A3\Sounds_F\arsenal\weapons_static\Mortar\reload_mortar", 1, 1, 20};
			reloadTime = 1.8;
			artilleryDispersion = 1.9;
			aiRateOfFire = 1;	// delay between shots at given distance
			aiRateOfFireDistance = 10;
			minRange = 0;
			minRangeProbab = 0.01;
			midRange = 1;
			midRangeProbab = 0.01;
			maxRange = 2;
			maxRangeProbab = 0.01;
		};
	};
	class AS_M57_weapon_Basic : mortar_82mm 
	{
        displayName = "M57 60mm Mortar";
        magazines[] = {
            "AS_HE_M73_Krusik_25x_Basic",
            "AS_Svetleca_M73_25x_Krusik_Basic",
            "AS_Dim_M73_Krusik_25x_Basic"
        };

        // Ponašanje oružja
        artilleryWeapon = 1;
        canLock = 0;
        weaponLockSystem = 0;

        // Jedan mod dovoljan – AI koristi skriptu za razne charge
        modes[] = {"Single"};

        class Single : Mode_SemiAuto {
            displayName = "M57 Fire";
            reloadTime = 2;
            sounds[] = {"StandardSound"};

            class StandardSound {
                soundSetShot[] = {"AS_M57_shot_soundset"};
            };

            // Ove vrednosti su čisto informativne – AI koristi charge preko skripte
            artilleryDispersion = 1.8;
            artilleryCharge = 0.85; // Default punjenje ako AI koristi bez override-a

            aiRateOfFire = 1;
            aiRateOfFireDistance = 500;
            minRange = 50; minRangeProbab = 0.1;
            midRange = 300; midRangeProbab = 0.7;
            maxRange = 1200; maxRangeProbab = 0.3;
        };

        // Zvukovi za punjenje
        reloadSound[] = {"A3\Sounds_F\arsenal\weapons_static\Mortar\reload_mortar", 1, 1, 20};
        reloadMagazineSound[] = {"A3\Sounds_F\arsenal\weapons_static\Mortar\reload_mortar", 1, 1, 20};
        magazineReloadTime = 1.5;
    };
	
	class ace_csw_staticMortarCarry : Launcher_Base_F {};
	
	class AS_M57_Carry : ace_csw_staticMortarCarry 
	{
		scope = 2;
		scopeCurator = 2;
		displayName = "M57 Cev i nozice";
		author = "Neo";
		model = "\AS_M57_Mortar\Zastava_M57_Mortar_Cev_i_nogare.p3d";
		picture = "\rhsafrf\addons\rhs_heavyweapons\bags\staticX_CA.paa";
		icon = "\rhsafrf\addons\rhs_heavyweapons\bags\mapIcon_backpack_CA.paa";
		
		class ACE_CSW {
			type = "weapon";
			deployTime = 5;
			pickupTime = 5;
			
			class assembleTo {
				AS_M57_baseplate = "AS_M57_Mortar";
			};
		};
		
		class WeaponSlotsInfo : WeaponSlotsInfo {
			class MuzzleSlot {
				iconScale = 0.1;
			};
			mass = 444;
		};
	};
	
	class ace_csw_carryMortarBaseplate : Launcher_Base_F {};
	
	class AS_M57_Postolje : ace_csw_carryMortarBaseplate 
	{
		scope = 2;
		scopeCurator = 2;
		mass = 382;
		displayName = "M57 Postolje";
		author = "Neo";
		picture = "\rhsafrf\addons\rhs_heavyweapons\bags\staticX_CA.paa";
		icon = "\rhsafrf\addons\rhs_heavyweapons\bags\mapIcon_backpack_CA.paa";
		
		class ACE_CSW {
			type = "mount";
			deployTime = 2;
			pickupTime = 2;
			deploy = "AS_M57_baseplate";
		};
		
		class WeaponSlotsInfo : WeaponSlotsInfo {
			mass = 154;
		};
	};
};

class CfgVehicles {
	class Land;	// External class reference
	
	class LandVehicle : Land {
		class Turrets;	// External class reference
	};
	
	class StaticWeapon : LandVehicle {
		class Turrets : Turrets {
			class MainTurret;	// External class reference
		};
	};
	
	class StaticMortar : StaticWeapon {
		class Turrets : Turrets {
			class MainTurret : MainTurret {
				class ViewGunner;	// External class reference
				class ViewOptics;	// External class reference
			};
		};
		class ACE_Actions;	// External class reference
		class ACE_SelfActions;
	};
	class C_man_1; // baza

class AS_M57_AI_Helper : C_man_1 {
    scope = 1; // skriven iz editora
    displayName = "Invisible Gunner";
    faction = "CIV_F"; 
    side = 3;
    vehicleClass = "Men";
    nakedUniform = "U_BasicBody";
    uniformClass = "U_BasicBody";

    weapons[] = {};
    respawnWeapons[] = {};
    magazines[] = {};
    respawnMagazines[] = {};
    backpack = "";

    camouflage = 0.01;
    sensitivity = 0;
    accuracy = 0;
    threat[] = {0, 0, 0};

    model = "\A3\characters_F\Common\invisibleMan.p3d";
    hiddenSelections[] = {};
    hiddenSelectionsTextures[] = {};

    identityTypes[] = {};

    // sve AI isključi
    class EventHandlers {
        init = "(_this select 0) hideObjectGlobal true; (_this select 0) disableAI 'ALL'; (_this select 0) allowDamage false;";
    };
};

	class AS_M57_Mortar : StaticMortar {
		artilleryScanner = 0;
		ace_artillerytables_showRangetable = 1;
		ace_artillerytables_showGunLaying = 1;
		scope = public;
		scopeCurator = 2;
		author = "Neo";
		displayName = "PPT M57 [ACE]";
		model = "AS_M57_Mortar\Zastava_M57_Mortar.p3d";
		editorPreview = "\AS_M57_Mortar\M57_3den_preview.paa";
		picture = "";
		side = TGuerrila;
		transportSoldier = 0;
		cargoAction[] = {"M57_Gunner"};
		getInAction = "GetInMortar";
		getOutAction = "GetOutLow";
		unitInfoType = "RscUnitInfoMortar";
		editorCategory = SAFP_CATEGORIE;
		editorSubcategory = SAFP_SUB_CATEGORIE_ARTILLERY;
		crew = "rhssaf_army_m10_digital_gl";
		cost = 200000;
		accuracy = 0.8;	
		EPEImpulseDamageCoef = 5;
		
		class AnimationSources {
			// class RoundHideSource {
				// weapon = "AS_M57_weapon";
				// selection = "round_selection";
				// source = "ammo";
				// type = "hide";
				// hideValue = 0;
				// unhideValue = 1;
			// };
			
			// class Mamasource {
				// weapon = "AS_M57_weapon";
				// selection = "round_selection";
				// source = "reloadMagazine";
			// };
			
			class LegsSource {
				selection = "legs";
				source = "mainGun";
			};
		};
		
		class Turrets : Turrets {
			class MainTurret : MainTurret {
				gunnerRightHandAnimName = "axis_right_hand";
				gunnerLeftHandAnimName = "axis_left_hand";
				gunnerAction = "M57_Gunner";
				gunnergetInAction = "GetInLow";
				gunnergetOutAction = "GetOutLow";
				weapons[] = {"AS_M57_weapon"};
				turretInfoType = "RscWeaponEmpty";
				elevationMode = 1;
				initCamElev = 0;
				minCamElev = -35;
				maxCamElev = 35;
				initElev = 0;
				minTurn = -12;
				maxTurn = 12;
				initTurn = 0;
				cameraDir = "gunner_dir";
				discreteDistance[] = {};
				gunnerForceOptics = false;
				memoryPointGunnerOptics = "gunnerview";
				gunnerOpticsModel = "AS_M57_Mortar\scope.p3d";
				gunnerUsesPilotView = true;
				disableSoundAttenuation = 1;
				stabilizedInAxes = 0;
				
				class ViewGunner : ViewGunner {
					initAngleX = -70;
					minAngleX = -360;
					maxAngleX = 360;
					initAngleY = -45;
					minAngleY = -360;
					maxAngleY = 360;
					initFov = 1;
					minFov = 1;
					maxFov = 1;
					visionMode[] = {"Normal"};
				};
				
				class ViewOptics : ViewOptics {
					camPos = "gunnerview";
					camDir = "gunner_dir";
					initAngleX = 0;
					minAngleX = -30;
					maxAngleX = 30;
					initAngleY = 0;
					minAngleY = -100;
					maxAngleY = 100;
					initFov = 0.15;
					minFov = 0.15;
					maxFov = 0.15;
					visionMode[] = {"Normal"};
				};
				minelev = 0;
				maxelev = 22;
				magazines[] = {};
				ejectDeadGunner = true;
				usepip = 2;
				discreteDistanceInitIndex = 0;
				primaryGunner = 1;
				maxHorizontalRotSpeed = 0.02;
				memoryPointsGetInGunner = "pos_gunner";
				memoryPointsGetInGunnerDir = "pos_gunner_dir";
				proxyType = "CPGunner";
				proxyIndex = 1;
			};
		};
		htMin = 1;
		htMax = 480;
		afMax = 0;
		mfMax = 0;
		mFact = 1;
		tBody = 100;
		ace_cargo_size = 2;
		ace_cargo_canLoad = 1;
		ace_dragging_canCarry = 1;
		ace_dragging_canDrag = 1;
		ace_dragging_carryPosition[] = {0, 1.2, 0};
		ace_dragging_dragPosition[] = {0, 1.2, 0};
		selectionDamage = "zbytek";
		ace_csw_isAssembled = 1;
		ace_csw_isDeployed = 1;
		ace_csw_enableCarry = 1;
		ace_csw_canBeCarried = 1;
		
		class DestructionEffects {
			class Smoke2 {
				intensity = 1;
				interval = 1;
				lifetime = 5;
				position = "konec hlavne";
				simulation = "particles";
				type = "WeaponWreckSmoke";
			};
			
			class Smoke {
				intensity = 1;
				interval = 1;
				lifetime = 5;
				position = "usti hlavne";
				simulation = "particles";
				type = "WeaponWreckSmoke";
			};
		};
		class ACE_SelfActions :ACE_SelfActions
		{
			class AS_LoadShellSelf 
			{
				condition = "alive _target";
				showDisabled = 1;
				priority = 5;
				displayName = "Ubaci Granatu";
				icon = "\x\TBD_MORTARS\addons\main\data\load.paa";
				
				class LoadHE0 
				{
					displayName = "M73 60mm Punjenje 0";
					icon = "\AS_M57_Mortar\M73_HE_Pic.paa";
					condition = "[_target, 0, ""AS_HE_M73_Krusik_0""] call TBD_MORTARS_main_fnc_checkCanLoadShell";
					statement = "[_target, 0, ""AS_HE_M73_Krusik_0""] call AS_M57_Mortar_fnc_loadShell";
					showDisabled = 0;
				};
				class LoadHE1 {
					displayName = "M73 60mm Punjenje 1";
					icon = "\AS_M57_Mortar\M73_HE_Pic.paa";
					condition = "[_target, 0, ""AS_HE_M73_Krusik_1""] call TBD_MORTARS_main_fnc_checkCanLoadShell";
					statement = "[_target, 0, ""AS_HE_M73_Krusik_1""] call AS_M57_Mortar_fnc_loadShell";
					showDisabled = 0;
				};
				
				class LoadHE2 {
					displayName = "M73 60mm Punjenje 2";
					icon = "\AS_M57_Mortar\M73_HE_Pic.paa";
					condition = "[_target, 0, ""AS_HE_M73_Krusik_2""] call TBD_MORTARS_main_fnc_checkCanLoadShell";
					statement = "[_target, 0, ""AS_HE_M73_Krusik_2""] call AS_M57_Mortar_fnc_loadShell";
					showDisabled = 0;
				};
				
				class LoadHE3 {
					displayName = "M73 60mm Punjenje 3";
					icon = "\AS_M57_Mortar\M73_HE_Pic.paa";
					condition = "[_target, 0, ""AS_HE_M73_Krusik_3""] call TBD_MORTARS_main_fnc_checkCanLoadShell";
					statement = "[_target, 0, ""AS_HE_M73_Krusik_3""] call AS_M57_Mortar_fnc_loadShell";
					showDisabled = 0;
				};
				
				class LoadHE4 {
					displayName = "M73 60mm Punjenje 4";
					icon = "\AS_M57_Mortar\M73_HE_Pic.paa";
					condition = "[_target, 0, ""AS_HE_M73_Krusik_4""] call TBD_MORTARS_main_fnc_checkCanLoadShell";
					statement = "[_target, 0, ""AS_HE_M73_Krusik_4""] call AS_M57_Mortar_fnc_loadShell";
					showDisabled = 0;
				};		
				class LoadSvetleca0 
				{
					displayName = "M73 60mm Punjenje 0";
					icon = "\AS_M57_Mortar\M73_Svetleca_Pic.paa";
					condition = "[_target, 0, ""AS_Svetleca_M73_Krusik_0""] call TBD_MORTARS_main_fnc_checkCanLoadShell";
					statement = "[_target, 0, ""AS_Svetleca_M73_Krusik_0""] call AS_M57_Mortar_fnc_loadShell";
					showDisabled = 0;
				};
				class LoadSvetleca1 {
					displayName = "Svetleca 60mm Punjenje 1";
					icon = "\AS_M57_Mortar\M73_Svetleca_Pic.paa";
					condition = "[_target, 0, ""AS_Svetleca_M73_Krusik_1""] call TBD_MORTARS_main_fnc_checkCanLoadShell";
					statement = "[_target, 0, ""AS_Svetleca_M73_Krusik_1""] call AS_M57_Mortar_fnc_loadShell";
					showDisabled = 0;
				};
				
				class LoadSvetleca2 {
					displayName = "M73 60mm Punjenje 2";
					icon = "\AS_M57_Mortar\M73_Svetleca_Pic.paa";
					condition = "[_target, 0, ""AS_Svetleca_M73_Krusik_2""] call TBD_MORTARS_main_fnc_checkCanLoadShell";
					statement = "[_target, 0, ""AS_Svetleca_M73_Krusik_2""] call AS_M57_Mortar_fnc_loadShell";
					showDisabled = 0;
				};
				
				class LoadSvetleca3 {
					displayName = "M73 60mm Punjenje 3";
					icon = "\AS_M57_Mortar\M73_Svetleca_Pic.paa";
					condition = "[_target, 0, ""AS_Svetleca_M73_Krusik_3""] call TBD_MORTARS_main_fnc_checkCanLoadShell";
					statement = "[_target, 0, ""AS_Svetleca_M73_Krusik_3""] call AS_M57_Mortar_fnc_loadShell";
					showDisabled = 0;
				};
				
				class LoadSvetleca4 {
					displayName = "M73 60mm Punjenje 4";
					icon = "\AS_M57_Mortar\M73_Svetleca_Pic.paa";
					condition = "[_target, 0, ""AS_Svetleca_M73_Krusik_4""] call TBD_MORTARS_main_fnc_checkCanLoadShell";
					statement = "[_target, 0, ""AS_Svetleca_M73_Krusik_4""] call AS_M57_Mortar_fnc_loadShell";
					showDisabled = 0;
				};				
				class LoadSmoke0 
				{
					displayName = "M73 60mm Dimna Punjenje 0";
					icon = "\AS_M57_Mortar\M73_Dimna_Pic.paa";
					condition = "[_target, 0, ""AS_Dim_M73_Krusik_0""] call TBD_MORTARS_main_fnc_checkCanLoadShell";
					statement = "[_target, 0, ""AS_Dim_M73_Krusik_0""] call AS_M57_Mortar_fnc_loadShell";
					showDisabled = 0;
				};	
				class LoadSmoke1 
				{
					displayName = "M73 60mm Dimna Punjenje 1";
					icon = "\AS_M57_Mortar\M73_Dimna_Pic.paa";
					condition = "[_target, 0, ""AS_Dim_M73_Krusik_1""] call TBD_MORTARS_main_fnc_checkCanLoadShell";
					statement = "[_target, 0, ""AS_Dim_M73_Krusik_1""] call AS_M57_Mortar_fnc_loadShell";
					showDisabled = 0;
				};
				
				class LoadSmoke2 {
					displayName = "M73 60mm Dimna Punjenje 2";
					icon = "\AS_M57_Mortar\M73_Dimna_Pic.paa";
					condition = "[_target, 0, ""AS_Dim_M73_Krusik_2""] call TBD_MORTARS_main_fnc_checkCanLoadShell";
					statement = "[_target, 0, ""AS_Dim_M73_Krusik_2""] call AS_M57_Mortar_fnc_loadShell";
					showDisabled = 0;
				};
				
				class LoadSmoke3 {
					displayName = "M73 60mm Dimna Punjenje 3";
					icon = "\AS_M57_Mortar\M73_Dimna_Pic.paa";
					condition = "[_target, 0, ""AS_Dim_M73_Krusik_3""] call TBD_MORTARS_main_fnc_checkCanLoadShell";
					statement = "[_target, 0, ""AS_Dim_M73_Krusik_3""] call AS_M57_Mortar_fnc_loadShell";
					showDisabled = 0;
				};
				
				class LoadSmoke4 {
					displayName = "M73 60mm Dimna Punjenje 4";
					icon = "\AS_M57_Mortar\M73_Dimna_Pic.paa";
					condition = "[_target, 0, ""AS_Dim_M73_Krusik_4""] call TBD_MORTARS_main_fnc_checkCanLoadShell";
					statement = "[_target, 0, ""AS_Dim_M73_Krusik_4""] call AS_M57_Mortar_fnc_loadShell";
					showDisabled = 0;
				};
			};
		};
		class ACE_Actions : ACE_Actions 
		{
			class TBD_LoadShell {
				selection = "usti hlavne";
				distance = 2.5;
				condition = "alive _target";
				showDisabled = 1;
				priority = 5;
				displayName = "Ubaci Granatu";
				icon = "\x\TBD_MORTARS\addons\main\data\load.paa";
				
				class LoadHE0 
				{
					displayName = "M73 60mm Punjenje 0";
					icon = "\AS_M57_Mortar\M73_HE_Pic.paa";
					condition = "[_target, 0, ""AS_HE_M73_Krusik_0""] call TBD_MORTARS_main_fnc_checkCanLoadShell";
					statement = "[_target, 0, ""AS_HE_M73_Krusik_0""] call AS_M57_Mortar_fnc_loadShell";
					showDisabled = 0;
				};
				class LoadHE1 {
					displayName = "M73 60mm Punjenje 1";
					icon = "\AS_M57_Mortar\M73_HE_Pic.paa";
					condition = "[_target, 0, ""AS_HE_M73_Krusik_1""] call TBD_MORTARS_main_fnc_checkCanLoadShell";
					statement = "[_target, 0, ""AS_HE_M73_Krusik_1""] call AS_M57_Mortar_fnc_loadShell";
					showDisabled = 0;
				};
				
				class LoadHE2 {
					displayName = "M73 60mm Punjenje 2";
					icon = "\AS_M57_Mortar\M73_HE_Pic.paa";
					condition = "[_target, 0, ""AS_HE_M73_Krusik_2""] call TBD_MORTARS_main_fnc_checkCanLoadShell";
					statement = "[_target, 0, ""AS_HE_M73_Krusik_2""] call AS_M57_Mortar_fnc_loadShell";
					showDisabled = 0;
				};
				
				class LoadHE3 {
					displayName = "M73 60mm Punjenje 3";
					icon = "\AS_M57_Mortar\M73_HE_Pic.paa";
					condition = "[_target, 0, ""AS_HE_M73_Krusik_3""] call TBD_MORTARS_main_fnc_checkCanLoadShell";
					statement = "[_target, 0, ""AS_HE_M73_Krusik_3""] call AS_M57_Mortar_fnc_loadShell";
					showDisabled = 0;
				};
				
				class LoadHE4 {
					displayName = "M73 60mm Punjenje 4";
					icon = "\AS_M57_Mortar\M73_HE_Pic.paa";
					condition = "[_target, 0, ""AS_HE_M73_Krusik_4""] call TBD_MORTARS_main_fnc_checkCanLoadShell";
					statement = "[_target, 0, ""AS_HE_M73_Krusik_4""] call AS_M57_Mortar_fnc_loadShell";
					showDisabled = 0;
				};	
				//--------------------------------------------------------------------------------------------------
				class LoadSvetleca0 
				{
					displayName = "M73 60mm Punjenje 0";
					icon = "\AS_M57_Mortar\M73_Svetleca_Pic.paa";
					condition = "[_target, 0, ""AS_Svetleca_M73_Krusik_0""] call TBD_MORTARS_main_fnc_checkCanLoadShell";
					statement = "[_target, 0, ""AS_Svetleca_M73_Krusik_0""] call AS_M57_Mortar_fnc_loadShell";
					showDisabled = 0;
				};
				class LoadSvetleca1 {
					displayName = "Svetleca 60mm Punjenje 1";
					icon = "\AS_M57_Mortar\M73_Svetleca_Pic.paa";
					condition = "[_target, 0, ""AS_Svetleca_M73_Krusik_1""] call TBD_MORTARS_main_fnc_checkCanLoadShell";
					statement = "[_target, 0, ""AS_Svetleca_M73_Krusik_1""] call AS_M57_Mortar_fnc_loadShell";
					showDisabled = 0;
				};
				
				class LoadSvetleca2 {
					displayName = "Svetleca 60mm Punjenje 2";
					icon = "\AS_M57_Mortar\M73_Svetleca_Pic.paa";
					condition = "[_target, 0, ""AS_Svetleca_M73_Krusik_2""] call TBD_MORTARS_main_fnc_checkCanLoadShell";
					statement = "[_target, 0, ""AS_Svetleca_M73_Krusik_2""] call AS_M57_Mortar_fnc_loadShell";
					showDisabled = 0;
				};
				
				class LoadSvetleca3 {
					displayName = "Svetleca 60mm Punjenje 3";
					icon = "\AS_M57_Mortar\M73_Svetleca_Pic.paa";
					condition = "[_target, 0, ""AS_Svetleca_M73_Krusik_3""] call TBD_MORTARS_main_fnc_checkCanLoadShell";
					statement = "[_target, 0, ""AS_Svetleca_M73_Krusik_3""] call AS_M57_Mortar_fnc_loadShell";
					showDisabled = 0;
				};
				
				class LoadSvetleca4 {
					displayName = "Svetleca 60mm Punjenje 4";
					icon = "\AS_M57_Mortar\M73_Svetleca_Pic.paa";
					condition = "[_target, 0, ""AS_Svetleca_M73_Krusik_4""] call TBD_MORTARS_main_fnc_checkCanLoadShell";
					statement = "[_target, 0, ""AS_Svetleca_M73_Krusik_4""] call AS_M57_Mortar_fnc_loadShell";
					showDisabled = 0;
				};	
				//--------------------------------------------------------------------------------------------------				
				class LoadSmoke0 
				{
					displayName = "M73 60mm Dimna Punjenje 0";
					icon = "\AS_M57_Mortar\M73_Dimna_Pic.paa";
					condition = "[_target, 0, ""AS_Dim_M73_Krusik_0""] call TBD_MORTARS_main_fnc_checkCanLoadShell";
					statement = "[_target, 0, ""AS_Dim_M73_Krusik_0""] call AS_M57_Mortar_fnc_loadShell";
					showDisabled = 0;
				};	
				class LoadSmoke1 
				{
					displayName = "M73 60mm Dimna Punjenje 1";
					icon = "\AS_M57_Mortar\M73_Dimna_Pic.paa";
					condition = "[_target, 0, ""AS_Dim_M73_Krusik_1""] call TBD_MORTARS_main_fnc_checkCanLoadShell";
					statement = "[_target, 0, ""AS_Dim_M73_Krusik_1""] call AS_M57_Mortar_fnc_loadShell";
					showDisabled = 0;
				};
				
				class LoadSmoke2 {
					displayName = "M73 60mm Dimna Punjenje 2";
					icon = "\AS_M57_Mortar\M73_Dimna_Pic.paa";
					condition = "[_target, 0, ""AS_Dim_M73_Krusik_2""] call TBD_MORTARS_main_fnc_checkCanLoadShell";
					statement = "[_target, 0, ""AS_Dim_M73_Krusik_2""] call AS_M57_Mortar_fnc_loadShell";
					showDisabled = 0;
				};
				
				class LoadSmoke3 {
					displayName = "M73 60mm Dimna Punjenje 3";
					icon = "\AS_M57_Mortar\M73_Dimna_Pic.paa";
					condition = "[_target, 0, ""AS_Dim_M73_Krusik_3""] call TBD_MORTARS_main_fnc_checkCanLoadShell";
					statement = "[_target, 0, ""AS_Dim_M73_Krusik_3""] call AS_M57_Mortar_fnc_loadShell";
					showDisabled = 0;
				};
				
				class LoadSmoke4 {
					displayName = "M73 60mm Dimna Punjenje 4";
					icon = "\AS_M57_Mortar\M73_Dimna_Pic.paa";
					condition = "[_target, 0, ""AS_Dim_M73_Krusik_4""] call TBD_MORTARS_main_fnc_checkCanLoadShell";
					statement = "[_target, 0, ""AS_Dim_M73_Krusik_4""] call AS_M57_Mortar_fnc_loadShell";
					showDisabled = 0;
				};
			};
			
			class TBD_UnLoadShell {
				selection = "usti hlavne";
				distance = 2.5;
				condition = "alive _target";
				showDisabled = 1;
				priority = 5;
				displayName = "Izbaci granatu";
				icon = "\x\TBD_MORTARS\addons\main\data\unload.paa";
				
				class UnloadHE0 {
					displayName = "M73 60mm Punjenje 0";
					icon = "\x\TBD_MORTARS\addons\120mm\tbd_mortar_120mm_shell_he\data\icon_120mm_he.paa";
					condition = "[_target, 0, ""AS_HE_M73_Krusik""] call TBD_MORTARS_main_fnc_checkCanUnloadShell";
					statement = "[_target, 0, ""AS_HE_M73_Krusik"", _player] call TBD_MORTARS_main_fnc_unloadShell";
					showDisabled = 0;
				};
				
				class UnloadHE1 {
					displayName = "M73 60mm Punjenje 1";
					icon = "\x\TBD_MORTARS\addons\120mm\tbd_mortar_120mm_shell_he\data\icon_120mm_he.paa";
					condition = "[_target, 0, ""AS_HE_M73_Krusik_1""] call TBD_MORTARS_main_fnc_checkCanUnloadShell";
					statement = "[_target, 0, ""AS_HE_M73_Krusik_1"", _player] call TBD_MORTARS_main_fnc_unloadShell";
					showDisabled = 0;
				};
				
				class UnloadHE2 {
					displayName = "M73 60mm Punjenje 2";
					icon = "\x\TBD_MORTARS\addons\120mm\tbd_mortar_120mm_shell_he\data\icon_120mm_he.paa";
					condition = "[_target, 0, ""AS_HE_M73_Krusik_2""] call TBD_MORTARS_main_fnc_checkCanUnloadShell";
					statement = "[_target, 0, ""AS_HE_M73_Krusik_2"", _player] call TBD_MORTARS_main_fnc_unloadShell";
					showDisabled = 0;
				};
				
				class UnloadHE3 {
					displayName = "M73 60mm Punjenje 3";
					icon = "\x\TBD_MORTARS\addons\120mm\tbd_mortar_120mm_shell_he\data\icon_120mm_he.paa";
					condition = "[_target, 0, ""AS_HE_M73_Krusik_3""] call TBD_MORTARS_main_fnc_checkCanUnloadShell";
					statement = "[_target, 0, ""AS_HE_M73_Krusik_3"", _player] call TBD_MORTARS_main_fnc_unloadShell";
					showDisabled = 0;
				};
				
				class UnloadHE4 {
					displayName = "M73 60mm Punjenje 4";
					icon = "\x\TBD_MORTARS\addons\120mm\tbd_mortar_120mm_shell_he\data\icon_120mm_he.paa";
					condition = "[_target, 0, ""AS_HE_M73_Krusik_4""] call TBD_MORTARS_main_fnc_checkCanUnloadShell";
					statement = "[_target, 0, ""AS_HE_M73_Krusik_4"", _player] call TBD_MORTARS_main_fnc_unloadShell";
					showDisabled = 0;
				};
			};
		};
		
		class ACE_CSW 
		{
			enabled = 1;
			disassembleTurret = "AS_M57_baseplate";
			disassembleWeapon = "AS_M57_Carry";
			disassembleFunc = "AS_M57_Mortar_fnc_handleDisassembly";
		};
	};
	class ace_csw_baseTripod;	// External class reference
	
	class ace_csw_mortarBaseplate : ace_csw_baseTripod {};
	
	class AS_M57_baseplate : ace_csw_mortarBaseplate {
		class ACE_CSW 
		{
			disassembleTo = "AS_M57_Postolje";
		};
		model = "AS_M57_Mortar\Zastava_M57_Mortar_postolje.p3d";
	};
	class AS_M57_Mortar_Bazicni : StaticMortar {
		artilleryScanner = 1;
		ace_artillerytables_showRangetable = 0;
		ace_artillerytables_showGunLaying = 0;
		scope = public;
		scopeCurator = 2;
		author = "Neo";
		displayName = "PPT M57 Bazicni";
		model = "AS_M57_Mortar\Zastava_M57_Mortar.p3d";
		editorPreview = "\AS_M57_Mortar\M57_3den_preview.paa";
		picture = "";
		side = TGuerrila;
		transportSoldier = 0;
		cargoAction[] = {"M57_Gunner"};
		getInAction = "GetInMortar";
		getOutAction = "GetOutLow";
		unitInfoType = "RscUnitInfoMortar";
		editorCategory = SAFP_CATEGORIE;
		editorSubcategory = SAFP_SUB_CATEGORIE_ARTILLERY;
		crew = "rhssaf_army_m10_digital_gl";
		cost = 200000;
		accuracy = 0.8;	
		EPEImpulseDamageCoef = 5;
		
		class AnimationSources {
			class RoundHideSource {
				weapon = "AS_M57_weapon";
				selection = "round_selection";
				source = "ammo";
				type = "hide";
				hideValue = 0;
				unhideValue = 1;
			};
			
			class Mamasource {
				weapon = "AS_M57_weapon";
				selection = "round_selection";
				source = "reloadMagazine";
			};
			
			class LegsSource {
				selection = "legs";
				source = "mainGun";
			};
		};
		
		class Turrets : Turrets 
		{
			class MainTurret : MainTurret 
			{
				gunnerRightHandAnimName = "axis_right_hand";
				gunnerLeftHandAnimName = "axis_left_hand";
				gunnerAction = "M57_Gunner";
				gunnergetInAction = "GetInLow";
				gunnergetOutAction = "GetOutLow";
				weapons[] = {"AS_M57_weapon_Basic"};
				magazines[] = 
				{
					"AS_HE_M73_Krusik_25x_Basic", 
					"AS_Svetleca_M73_25x_Krusik_Basic", 
					"AS_Dim_M73_Krusik_25x_Basic"
				};
				turretInfoType = "RscWeaponEmpty";
				elevationMode = 1;
				initCamElev = 0;
				minCamElev = -35;
				maxCamElev = 35;
				initElev = 0;
				initTurn = 0;
				minElev = 0;
				maxElev = 45;
				minTurn = -180;
				maxTurn = 180;
				//cameraDir = "gunnerview";
				discreteDistance[] = {};
				gunnerForceOptics = false;
				memoryPointGunnerOptics = "gunnerview";
				gunnerOpticsModel = "AS_M57_Mortar\scope.p3d";
				gunnerUsesPilotView = true;
				disableSoundAttenuation = 1;
				stabilizedInAxes = 0;
				
				class ViewGunner : ViewGunner {
					initAngleX = -70;
					minAngleX = -360;
					maxAngleX = 360;
					initAngleY = -45;
					minAngleY = -360;
					maxAngleY = 360;
					initFov = 1;
					minFov = 1;
					maxFov = 1;
					visionMode[] = {"Normal"};
				};
				
				class ViewOptics : ViewOptics {
					initAngleX = 0;
					minAngleX = -30;
					maxAngleX = 30;
					initAngleY = 0;
					minAngleY = -100;
					maxAngleY = 100;
					initFov = 0.15;
					minFov = 1;
					maxFov = 1;
					visionMode[] = {"Normal"};
				};
				ejectDeadGunner = true;
				usepip = 2;
				discreteDistanceInitIndex = 0;
				primaryGunner = 1;
				maxHorizontalRotSpeed = 1;
				memoryPointsGetInGunner = "pos_gunner";
				memoryPointsGetInGunnerDir = "pos_gunner_dir";
				proxyType = "CPGunner";
				proxyIndex = 1;
			};
		};
		htMin = 1;
		htMax = 480;
		afMax = 0;
		mfMax = 0;
		mFact = 1;
		tBody = 100;
		ace_cargo_size = 2;
		ace_cargo_canLoad = 1;
		ace_dragging_canCarry = 1;
		ace_dragging_canDrag = 1;
		ace_dragging_carryPosition[] = {0, 1.2, 0};
		ace_dragging_dragPosition[] = {0, 1.2, 0};
		selectionDamage = "zbytek";
		ace_csw_isAssembled = 1;
		ace_csw_isDeployed = 1;
		ace_csw_enableCarry = 1;
		ace_csw_canBeCarried = 1;
		
		class DestructionEffects {
			class Smoke2 {
				intensity = 1;
				interval = 1;
				lifetime = 5;
				position = "konec hlavne";
				simulation = "particles";
				type = "WeaponWreckSmoke";
			};
			
			class Smoke {
				intensity = 1;
				interval = 1;
				lifetime = 5;
				position = "usti hlavne";
				simulation = "particles";
				type = "WeaponWreckSmoke";
			};
		};
	};
	class EAST_Box_Base;	// External class reference
	
	class AS_M57_Sanduk : EAST_Box_Base {
		editorPreview = "AS_M57_Mortar\as_M57_box\data\preview.paa";
		displayName = "M57 HE granate 12 komada";
		scope = public;
		model = "AS_M57_Mortar\as_M57_box\M57_ammo_box.p3d";
		icon = "iconCrateLarge";
		transportMaxWeapons = 200;
		transportMaxMagazines = 1000;
		author = "Neo";
		
		class TransportWeapons {};
		
		class TransportMagazines {
			class _xx_AS_HE_M73_Krusik_1 {
				magazine = "AS_HE_M73_Krusik_1";
				count = 12;
			};	
		};
		
		class TransportItems {};
	};	
	class AS_M57_Sanduk_Dimne : EAST_Box_Base 
	{
		editorPreview = "AS_M57_Mortar\as_M57_box\data\preview.paa";
		displayName = "M57 Dimne granate 12 komada";
		scope = public;
		model = "AS_M57_Mortar\as_M57_box\M57_ammo_box.p3d";
		icon = "iconCrateLarge";
		transportMaxWeapons = 200;
		transportMaxMagazines = 1000;
		author = "Neo";
		
		class TransportWeapons {};
		
		class TransportMagazines {	
			class _xx_AS_Dim_M73_Krusik_1 
			{
				magazine = "AS_Dim_M73_Krusik_1";
				count = 12;
			};
		};
		
		class TransportItems {};
	};	
	class AS_M57_Sanduk_Svetleca : EAST_Box_Base 
	{
		editorPreview = "AS_M57_Mortar\as_M57_box\data\preview.paa";
		displayName = "M57 Svetlece granate 12 komada";
		scope = public;
		model = "AS_M57_Mortar\as_M57_box\M57_ammo_box.p3d";
		icon = "iconCrateLarge";
		transportMaxWeapons = 200;
		transportMaxMagazines = 1000;
		author = "Neo";
		
		class TransportWeapons {};
		
		class TransportMagazines {	
			class _xx_AS_Svetleca_M73_Krusik_1
			{
				magazine = "AS_Svetleca_M73_Krusik_1";
				count = 12;
			};
		};
		
		class TransportItems {};
	};
	class M57_Komplet_Sanduk : EAST_Box_Base 
	{
			editorPreview = "rhsafrf\addons\rhs_editorPreviews\data\rhs_7ya37_1_single.paa";
			scope = public;
			author = "Neo";
			displayName = "M57 Komplet";
			model = "rhsafrf\addons\rhs_weapons\crates\rhs_3Ya40_1_single";
			transportMaxWeapons = 10;
			transportMaxMagazines = 50;
				
			class TransportWeapons 
			{
				class _xx_AS_M57_Carry
				{
						weapon = "AS_M57_Carry";
						count = 1;
				};	
				class _xx_AS_M57_Postolje
				{
						weapon = "AS_M57_Postolje";
						count = 1;
				};
			};
			class TransportItems {};
	};
};
